PORT: 8080
REST_HOST: "0.0.0.0"
JWT_SECRET: "your-secret-key-here"

POSTGRES:
  host: "postgres"
  port: 5432
  username: "forumuser"
  password: "qwerty1234"
  database: "forumdb"
  min_conns: 5
  max_conns: 10
